FIX: use commit count for revision
User commit count for revision if no annotated revision tag found.

diff --git a/config/revision-gen b/config/revision-gen
--- a/config/revision-gen
+++ b/config/revision-gen
@@ -30,7 +30,11 @@ if [ "$?" != "0" ]; then
     VER_REV=v`git describe --abbrev=5 --match="${VERSION}" HEAD`
     if [ "$?" != "0" ]; then
 	echo "Could not find tag $VERSION" 1>&2
-	exit 1
+	VER_REV=`git rev-list --all --count`
+	if [ "$?" != "0" ]; then
+	    echo "Could not find tag $VERSION" 1>&2
+	    exit 1
+	fi;
     fi
 fi
 REV=`echo "${VER_REV}" | sed -e 's/^v[0-9\.]\+-//g' -e 's/-g\?/./g'`
