Add: tag format without leaidng v char

diff --git a/config/revision-gen b/config/revision-gen
--- a/config/revision-gen
+++ b/config/revision-gen
@@ -27,7 +27,11 @@ VERSION=$1
 VER_REV=`git describe --abbrev=5 --match="v${VERSION}" HEAD`
 if [ "$?" != "0" ]; then
     echo "Could not find tag v$VERSION" 1>&2
-    exit 1
+    VER_REV=`git describe --abbrev=5 --match="${VERSION}" HEAD`
+    if [ "$?" != "0" ]; then
+	echo "Could not find tag $VERSION" 1>&2
+	exit 1
+    fi
 fi
 REV=`echo "${VER_REV}" | sed -e 's/^v[0-9.]\+-//g' -e 's/-g\?/./g'`
 if [ -n "$parent_rev" ]; then
